"""Report writers for AgentBOM."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_reports(bom: dict[str, Any], output_dir: str | Path, pretty: bool = False) -> tuple[Path, Path]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    json_path = out / "agentbom.json"
    md_path = out / "agentbom.md"

    indent = 2 if pretty else None
    json_path.write_text(json.dumps(bom, indent=indent, sort_keys=pretty) + "\n", encoding="utf-8")
    md_path.write_text(render_markdown(bom), encoding="utf-8")
    return json_path, md_path


def render_markdown(bom: dict[str, Any]) -> str:
    lines = [
        "# AgentBOM",
        "",
        f"- Schema version: {bom['schema_version']}",
        f"- Repository: {bom['repository']}",
        f"- Generated by: {bom['generated_by']}",
        "",
    ]

    lines.extend(_model_section(bom.get("models", [])))
    lines.extend(_section("Providers", bom.get("providers", bom.get("models", []))))
    lines.extend(_section("Frameworks", bom["frameworks"]))
    lines.extend(_section("MCP Config Files", bom["mcp_servers"]))
    lines.extend(_section("Prompt Files", bom["prompts"]))
    lines.extend(_section("Capabilities", bom["capabilities"]))
    lines.extend(_section("Secret References", bom["secret_references"]))
    lines.extend(_risk_section(bom["risks"]))
    return "\n".join(lines).rstrip() + "\n"


def _section(title: str, items: list[dict[str, str]]) -> list[str]:
    lines = [f"## {title}", ""]
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        label = item.get("name") or item.get("path") or item.get("type", "item")
        path = item.get("path")
        confidence = item.get("confidence")
        detail = f" ({path})" if path and path != label else ""
        if confidence:
            detail += f" [{confidence}]"
        lines.append(f"- {label}{detail}")
    lines.append("")
    return lines


def _model_section(items: list[dict[str, str]]) -> list[str]:
    lines = ["## Models", ""]
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        name = item.get("name", "model")
        source_file = item.get("source_file")
        confidence = item.get("confidence")
        detail = f" ({source_file})" if source_file else ""
        if confidence:
            detail += f" [{confidence}]"
        lines.append(f"- {name}{detail}")
    lines.append("")
    return lines


def _risk_section(risks: list[dict[str, str]]) -> list[str]:
    lines = ["## Risks", ""]
    if not risks:
        lines.extend(["None detected.", ""])
        return lines
    for risk in risks:
        lines.append(f"- {risk['severity']}: {risk['reason']}")
    lines.append("")
    return lines
